spring:
  config:
    activate:
      on-profile: receiver

grpc:
  client:
    sender:
      address: ${GRPC_SENDER_ADDRESS:static://localhost:9091}
      negotiationType: PLAINTEXT
    serverapp:
      address: ${GRPC_SERVERAPP_ADDRESS:static://localhost:9093}
      negotiationType: PLAINTEXT
